### ISSUE TITLE
Mining Not Working

### ISSUE THREAD

**Issue by rioagungpurnomo** [HugoXOX3/PythonMiner#2]
Version : [1.2.3](https://github.com/HugoXOX3/PythonMiner/releases/tag/Minerv1.2.3)

Hi developers

Please fix the problem, here is a picture of the error
![IMG_20240618_132622](https://github.com/HugoXOX3/PythonMiner/assets/161745412/f762df3c-811e-4ea2-997c-3038ef0c391c)

**Comment by HugoXOX3** [comment]
Thanks For your issue.Right now I am fixing and you need to comfim that you can connect to ckpool.If not,you shall use a VPN or proxy pool

**Comment by HugoXOX3** [comment]
You should try this [New Version](https://github.com/HugoXOX3/PythonMiner/releases/tag/Minerv1.3.1)
